version: 2
jobs:
  build:
    general:
      branches:
        only:
         - develop # list of branches to build
    docker:
      - image: circleci/python:3.5.6-browsers-legacy
    steps:
      - checkout
      - run: echo "A first hello"
      - run:
         name: Code Has Arrived
         command: |
           ls -al
           echo '^^^That should look familiar^^^'
