version: 2
jobs:
  Build:
    general:
      branches:
        only:
         - develop # list of branches to build
    docker:
      - image: circleci/python:3.5.6-browsers-legacy
    steps:
      - checkout
      # - run: echo "A first hello"
  Deploy:
    docker:
     - image: circleci/python:3.5.6-browsers-legacy
    steps:
    #  - checkout
     - run:
         name: run virtual python environment
         command: |
           cd microblog
           source mblog-venv/bin/activate
  Run-With-Node:
   docker:
     - image: circleci/python:3.5.6-browsers-legacy
   steps:
     - run:
        name: Running in a Unique Container
        command: |
          python --version
  Now-Complete:
   docker:
     - image: circleci/python:3.5.6-browsers-legacy
   steps:
     - run:
         name: Approval Complete
         command: |
           echo 'Do work once the approval has completed'

workflows:
 version: 2
 Example_Workflow:
   jobs:
     - Build
     - Deploy:
         requires:
           - Build
    #  - Run-With-Node:
    #      requires:
    #        - Build
    #  - Hold-For-Approval:
    #      type: approval
    #      requires:
    #        - Run-With-Node
    #        - Deploy
    #  - Now-Complete:
    #      requires:
    #        - Hold-For-Approval
